name: Do a Duolingo lesson

on:
  workflow_dispatch:
    inputs:
      lessons:
        default: 5
        description: 'Number of lessons to be completed'
        required: false
        type: number
  schedule:
    - cron: '0 7-8 * * *'

jobs:
  study:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: ${{ inputs.lessons || 5 }}

      - name: Sleep for 20 seconds
        run: sleep 15

      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: 6

      - name: Sleep for 20 seconds
        run: sleep 20

      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: 5

      - name: Sleep for 20 seconds
        run: sleep 14

      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: 6

      - name: Sleep for 20 seconds
        run: sleep 13

      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: 4

      - name: Sleep for 20 seconds
        run: sleep 16

      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: 5

      - name: Sleep for 20 seconds
        run: sleep 17

      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: 4

      - name: Sleep for 20 seconds
        run: sleep 18

      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: 3

      - name: Sleep for 20 seconds
        run: sleep 28

      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: 5

      - name: Sleep for 20 seconds
        run: sleep 20

      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: 6

      - name: Sleep for 20 seconds
        run: sleep 21

      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: 5

      - name: Sleep for 20 seconds
        run: sleep 20

      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: 4

      - name: Sleep for 20 seconds
        run: sleep 12

      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: 6
